### ISSUE TITLE
Bad Chapter Links

### ISSUE THREAD

**Issue by nicholasviau** [kuriwaki/prefresher#49]
* **Chapter 3 - Limits** and **Chapter 6 - Probability** link to the _Pre-Prefresher Exercises_ sections with the same names.

**Comment by kuriwaki** [comment]
Thank you for pointing this out. I've noticed but it may be a bookdown issue. I set `collapse: section` so that subsection headers are hidden in the first page, but clicking on the link to "Limits" sends you to the link that would be there if subsections were not collapsed. By chance, this happens to be the subsections you mention. I might need to un-display the subsections for just the pre-prefresher chapter.

**Comment by kuriwaki** [comment]
Looks like this got caught as a duplicate chapter label (even though only one was untagged). 

quoting https://bookdown.org/yihui/bookdown/new-session.html: 

* Because knitr does not allow duplicate chunk labels in a source document, you need to make sure there are no duplicate labels in your book chapters when you use the M-K approach, otherwise knitr will signal an error when knitting the merged Rmd file. Note that this means there must not be duplicate labels throughout the whole book. The K-M approach only requires no duplicate labels within any single Rmd file.
* K-M does not allow Rmd files to be in subdirectories, but M-K does.

The default approach in bookdown is M-K. To switch to K-M, you either use the argument new_session = TRUE when calling render_book(), or set new_session: yes in the configuration file _bookdown.yml.

Will rename and close. thanks!

**Comment by kuriwaki** [comment]
now fixed in master and on the server (https://bookdown.org/kuriwaki/prefresher/). Thank you @nicholasviau.
